namedAddresses:
  "0x1": aptos_framework
  "0x3": aptos_token
  "0x4": aptos_token_objects
  "0x2cca48b8b0d7f77ef28bfd608883c599680c5b8db8192c5e3baaae1aee45114c": args_test_suite
  "0xabcde341afbc4d846a4453bf042dffe74a137c0f0b50c548a87f726f4b1d62ed": monsters
  "0x7e783b349d3e89cf5931af376ebeadbfab855b3fa239b7ada8f5a92fbea6b387": pyth
  "0x7d7e436f0b2aafde60774efb26ccc432cf881b677aca7faaf2a01879bd19fb8": switchboard
namedTypeTags:
  "0x4::token::Token": "Token"
  "0x4::collection::Collection": "Collection"

structArgs: false
outputPath: "./generated/"
functionComments: true
expandedStructs: false
replaceNamedAddresses: true
payloadBCSTypesFilename: "bcsPayloadTypes"
includeAccountParams: false # set this to `true` if you have access to all the private keys. `false` if you're doing dapp development
separateViewAndEntryFunctionsByNamespace: false
viewFunctionsNamespace: "ViewFuncs"
entryFunctionsNamespace: "EntryFuncs"
sdkPath: "@aptos-labs/ts-sdk"
